# Generated by Django 6.0 on 2026-01-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_assessment'),
        ('patient', '0002_patient_diagnosis_patient_gender_patient_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='related_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='patient.patient'),
        ),
    ]
