# Generated by Django 6.0 on 2026-01-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_assessment_related_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='image_full_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
