# Generated by Django 6.0 on 2026-01-29 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_uploadedimage_image_full_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.assessment')),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.uploadedimage')),
            ],
            options={
                'db_table': 'images_assessment_images',
            },
        ),
        migrations.AlterField(
            model_name='assessment',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='assessments', through='images.AssessmentImage', to='images.uploadedimage'),
        ),
    ]
