# Generated by Django 6.0 on 2026-01-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_assessmentimage_alter_assessment_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='stage',
            field=models.CharField(default='Stage 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentimage',
            name='uploaded_image',
            field=models.ForeignKey(db_column='uploadedimage_id', on_delete=django.db.models.deletion.CASCADE, to='images.uploadedimage'),
        ),
    ]
