# Generated by Django 6.0 on 2026-01-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_assessment_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='body_part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='depth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='exudate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pain_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='width',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='wound_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
