# Generated by Django 6.0 on 2026-01-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_diagnosis_patient_gender_patient_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigning_physician',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
